return {
	-- {
	-- 	"GCBallesteros/jupytext.nvim",
	-- 	lazy = false,
	-- 	config = function()
	-- 		require("jupytext").setup({
	-- 			style = "markdown",
	-- 			output_extension = "md",
	-- 			force_ft = "markdown",
	-- 		})
	-- 	end,
	-- },
	-- {
	-- 	"jmbuhr/otter.nvim",
	-- 	dependencies = {
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 	},
	-- 	opts = {},
	-- },
	-- {
	-- 	"quarto-dev/quarto-nvim",
	-- 	ft = { "quarto", "markdown" },
	-- 	dependencies = {
	-- 		"jmbuhr/otter.nvim",
	-- 		"nvim-treesitter/nvim-treesitter",
	-- 	},
	--
	-- 	opts = {
	-- 		codeRunner = {
	-- 			enabled = true,
	-- 			default_method = "molten", -- "molten", "slime", "iron" or <function>
	-- 			ft_runners = {}, -- filetype to runner, ie. `{ python = "molten" }`.
	-- 			-- Takes precedence over `default_method`
	-- 			never_run = { "yaml" }, -- filetypes which are never sent to a code runner
	-- 		},
	-- 		setup = function()
	-- 			local runner = require("quarto.runner")
	-- 			vim.keymap.set(
	-- 				"n",
	-- 				"<localleader>rc",
	-- 				runner.run_cell,
	-- 				{ desc = "run cell", silent = true }
	-- 			)
	-- 			vim.keymap.set(
	-- 				"n",
	-- 				"<localleader>ra",
	-- 				runner.run_above,
	-- 				{ desc = "run cell and above", silent = true }
	-- 			)
	--
	-- 			vim.keymap.set(
	-- 				"n",
	-- 				"<localleader>rA",
	-- 				runner.run_all,
	-- 				{ desc = "run all cells", silent = true }
	-- 			)
	-- 			vim.keymap.set(
	-- 				"n",
	-- 				"<localleader>rl",
	-- 				runner.run_line,
	-- 				{ desc = "run line", silent = true }
	-- 			)
	-- 			vim.keymap.set(
	-- 				"v",
	-- 				"<localleader>r",
	-- 				runner.run_range,
	-- 				{ desc = "run visual range", silent = true }
	-- 			)
	-- 			vim.keymap.set("n", "<localleader>RA", function()
	-- 				runner.run_all(true)
	-- 			end, { desc = "run all cells of all languages", silent = true })
	-- 		end,
	-- 	},
	-- },
	-- {
	-- 	"benlubas/molten-nvim",
	-- 	version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
	-- 	dependencies = { "3rd/image.nvim" },
	-- 	build = ":UpdateRemotePlugins",
	-- 	ft = { "markdown" },
	-- 	init = function()
	-- 		-- these are examples, not defaults. Please see the readme
	-- 		vim.g.molten_image_provider = "image.nvim"
	-- 		vim.g.molten_output_win_max_height = 20
	-- 		-- I find auto open annoying, keep in mind setting this option will require setting
	-- 		-- a keybind for `:noautocmd MoltenEnterOutput` to open the output again
	-- 		vim.g.molten_auto_open_output = false
	--
	-- 		-- optional, I like wrapping. works for virt text and the output window
	-- 		vim.g.molten_wrap_output = true
	--
	-- 		-- Output as virtual text. Allows outputs to always be shown, works with images, but can
	-- 		-- be buggy with longer images
	-- 		vim.g.molten_virt_text_output = true
	--
	-- 		-- this will make it so the output shows up below the \`\`\` cell delimiter
	-- 		vim.g.molten_virt_lines_off_by_1 = true
	--
	-- 		vim.keymap.set(
	-- 			"n",
	-- 			"<localleader>e",
	-- 			":MoltenEvaluateOperator<CR>",
	-- 			{ desc = "evaluate operator", silent = true }
	-- 		)
	-- 		vim.keymap.set(
	-- 			"n",
	-- 			"<localleader>os",
	-- 			":noautocmd MoltenEnterOutput<CR>",
	-- 			{ desc = "open output window", silent = true }
	-- 		)
	--
	-- 		vim.keymap.set(
	-- 			"n",
	-- 			"<localleader>rr",
	-- 			":MoltenReevaluateCell<CR>",
	-- 			{ desc = "re-eval cell", silent = true }
	-- 		)
	-- 		vim.keymap.set(
	-- 			"v",
	-- 			"<localleader>r",
	-- 			":<C-u>MoltenEvaluateVisual<CR>gv",
	-- 			{ desc = "execute visual selection", silent = true }
	-- 		)
	-- 		vim.keymap.set(
	-- 			"n",
	-- 			"<localleader>oh",
	-- 			":MoltenHideOutput<CR>",
	-- 			{ desc = "close output window", silent = true }
	-- 		)
	-- 		vim.keymap.set(
	-- 			"n",
	-- 			"<localleader>md",
	-- 			":MoltenDelete<CR>",
	-- 			{ desc = "delete Molten cell", silent = true }
	-- 		)
	--
	-- 		-- if you work with html outputs:
	-- 		vim.keymap.set(
	-- 			"n",
	-- 			"<localleader>mx",
	-- 			":MoltenOpenInBrowser<CR>",
	-- 			{ desc = "open output in browser", silent = true }
	-- 		)
	-- 	end,
	-- },
	-- {
	-- 	"3rd/image.nvim",
	-- 	build = false,
	-- 	opts = {
	-- 		processor = "magick_cli",
	-- 		max_width = 100,
	-- 		max_height = 12,
	-- 		max_height_window_percentage = math.huge,
	-- 		max_width_window_percentage = math.huge,
	-- 		window_overlap_clear_enabled = true,
	-- 		window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
	-- 	},
	-- },
}
